---
- name: Add repository
  apt_repository:
    repo: "ppa:openjdk-r/ppa"
    update_cache: true

- name: Install packages
  apt:
    package: "{{ item }}"
    state: present
  with_items:
    - openjdk-8-jdk
    - openjdk-8-jre
    - openjdk-8-jre-headless

- name: Remove other java versions
  apt:
    package: "{{ item }}"
    state: absent
  with_items:
    - openjdk-7-jdk
    - openjdk-7-jre
    - openjdk-7-jre-headless
    - openjdk-9-jdk
    - openjdk-9-jre
    - openjdk-9-jre-headless